import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import Chart from 'chart.js/auto';
import { ReportData, DetailedReportContent, CalculatedProduct } from '../types';

const COLORS = {
    primary: '#1e3a8a', // Deep Blue
    secondary: '#3b82f6', // Bright Blue
    textDark: '#111827',
    textLight: '#4b5563',
    white: '#ffffff',
    bgLight: '#f3f4f6',
    success: '#10b981', // Green
    warning: '#f59e0b', // Amber
    danger: '#ef4444', // Red
};

const PAGE_MARGIN = 20;

// --- Helper Functions ---

const addHeader = (doc: jsPDF, title: string) => {
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Logo / Brand Mark
    doc.setFillColor(COLORS.primary);
    doc.rect(PAGE_MARGIN, 15, 10, 10, 'F');
    doc.setFontSize(10);
    doc.setTextColor(COLORS.primary);
    doc.setFont('helvetica', 'bold');
    doc.text('MSPCC.ai', PAGE_MARGIN + 14, 21);

    // Title
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(COLORS.textDark);
    doc.text(title.toUpperCase(), PAGE_MARGIN, 40);
    
    // Divider
    doc.setDrawColor(COLORS.secondary);
    doc.setLineWidth(0.5);
    doc.line(PAGE_MARGIN, 45, pageWidth - PAGE_MARGIN, 45);
};

const addFooter = (doc: jsPDF) => {
    const pageCount = (doc as any).internal.getNumberOfPages();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(COLORS.textLight);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - PAGE_MARGIN, pageHeight - 10, { align: 'right' });
        doc.text('Confidential Business Report | Generated by MSPCC.ai', PAGE_MARGIN, pageHeight - 10);
    }
};

const addSectionTitle = (doc: jsPDF, title: string, y: number) => {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(COLORS.primary);
    doc.text(title.toUpperCase(), PAGE_MARGIN, y);
    return y + 10;
};

// --- Chart Generation ---

const generateChartImage = async (type: 'bar' | 'line' | 'doughnut' | 'pie', data: any, options: any = {}): Promise<string> => {
    const canvas = document.createElement('canvas');
    canvas.width = 800; // High resolution for PDF
    canvas.height = 400;
    const ctx = canvas.getContext('2d');
    if (!ctx) return '';

    const chart = new Chart(ctx, {
        type: type,
        data: data,
        options: {
            ...options,
            responsive: false,
            animation: false,
            devicePixelRatio: 2, // Ensure sharpness
            plugins: {
                legend: {
                    labels: { font: { size: 14 } }
                }
            },
            scales: options.scales || {
                x: { ticks: { font: { size: 14 } } },
                y: { ticks: { font: { size: 14 } } }
            }
        }
    });

    const imgData = canvas.toDataURL('image/png');
    chart.destroy();
    return imgData;
};


// --- Page Generators ---

const generateCoverPage = (doc: jsPDF, reportData: DetailedReportContent) => {
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Background Gradient (Simulated with rect)
    doc.setFillColor(COLORS.primary);
    doc.rect(0, 0, pageWidth, pageHeight * 0.4, 'F');

    // Title
    doc.setTextColor(COLORS.white);
    doc.setFontSize(28);
    doc.setFont('helvetica', 'bold');
    doc.text("WEEKLY PERFORMANCE", PAGE_MARGIN, 60);
    doc.text("AUDIT REPORT", PAGE_MARGIN, 75);

    // Subtitle
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(220, 220, 255);
    doc.text("Comprehensive Analysis of Sales, Inventory & Profitability", PAGE_MARGIN, 90);

    // Info Box
    const infoY = 160;
    doc.setTextColor(COLORS.textDark);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("REPORT DETAILS", PAGE_MARGIN, infoY);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(COLORS.textLight);
    doc.text(`Date Generated: ${reportData.reportDate}`, PAGE_MARGIN, infoY + 10);
    doc.text(`Prepared For: Business Owner`, PAGE_MARGIN, infoY + 18);
    doc.text(`Analysis Scope: Weekly Product Snapshot`, PAGE_MARGIN, infoY + 26);
    
    // Status Badge
    doc.setFillColor(COLORS.success);
    doc.roundedRect(pageWidth - 60, infoY - 5, 40, 12, 2, 2, 'F');
    doc.setTextColor(COLORS.white);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text("VERIFIED DATA", pageWidth - 55, infoY + 2);
};

const generateTOC = (doc: jsPDF) => {
    doc.addPage();
    addHeader(doc, "Table of Contents");
    
    const contents = [
        "1. Executive Summary",
        "2. Data Quality & Integrity",
        "3. Key Performance Indicators",
        "4. Category Analysis",
        "5. Market Analysis",
        "6. Strategic Recommendations",
        "7. Detailed Product Data",
    ];

    let y = 60;
    doc.setFontSize(11);
    doc.setTextColor(COLORS.textDark);
    
    contents.forEach(item => {
        doc.text(item, PAGE_MARGIN, y);
        doc.setDrawColor(230, 230, 230);
        doc.line(PAGE_MARGIN, y + 4, 190, y + 4);
        y += 15;
    });
};

const generateExecutiveSummary = (doc: jsPDF, data: DetailedReportContent['executiveSummary'], trendChartImg: string) => {
    doc.addPage();
    addHeader(doc, "Executive Summary");
    
    let y = 60;
    doc.setFontSize(10);
    doc.setTextColor(COLORS.textDark);
    const lines = doc.splitTextToSize(data.overview, 170);
    doc.text(lines, PAGE_MARGIN, y);
    y += lines.length * 5 + 15;

    // Key Metrics Grid
    addSectionTitle(doc, "Key Metrics at a Glance", y);
    y += 10;
    
    autoTable(doc, {
        startY: y,
        head: [['Metric', 'Value', 'Status']],
        body: data.keyMetrics.map(m => [m.label, m.value, m.status]),
        theme: 'grid',
        headStyles: { fillColor: COLORS.bgLight, textColor: COLORS.textDark, fontStyle: 'bold', lineWidth: 0 },
        columnStyles: {
            0: { fontStyle: 'bold', cellWidth: 80 },
            2: { cellWidth: 40, fontStyle: 'bold', halign: 'center' }
        },
        styles: { fontSize: 10, cellPadding: 6, lineColor: 230 },
        didParseCell: (data) => {
            if (data.section === 'body' && data.column.index === 2) {
                const status = data.cell.raw;
                if (status === 'Positive') data.cell.styles.textColor = COLORS.success;
                if (status === 'Negative') data.cell.styles.textColor = COLORS.danger;
                if (status === 'Neutral') data.cell.styles.textColor = COLORS.warning;
            }
        }
    });

    // Add Trend Chart
    const finalY = (doc as any).lastAutoTable.finalY + 15;
    if (finalY + 80 < doc.internal.pageSize.getHeight()) {
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(COLORS.primary);
        doc.text("Weekly Profit Trend", PAGE_MARGIN, finalY);
        
        doc.addImage(trendChartImg, 'PNG', PAGE_MARGIN, finalY + 5, 170, 80);
    }
};

const generateDataQuality = (doc: jsPDF, data: DetailedReportContent['dataQuality']) => {
    doc.addPage();
    addHeader(doc, "Data Quality Assessment");

    let y = 60;
    
    // Summary
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(data.summary, 170);
    doc.text(lines, PAGE_MARGIN, y);
    y += lines.length * 5 + 10;
    
    // Score Badge
    doc.setFontSize(12);
    doc.text(`Overall Data Health:`, PAGE_MARGIN, y);
    doc.setTextColor(data.score === 'Excellent' || data.score === 'Good' ? COLORS.success : COLORS.danger);
    doc.setFont('helvetica', 'bold');
    doc.text(data.score.toUpperCase(), PAGE_MARGIN + 45, y);
    doc.setTextColor(COLORS.textDark);
    y += 15;

    // Quality Table
    autoTable(doc, {
        startY: y,
        head: [['Quality Check', 'Status', 'Details']],
        body: data.checks.map(c => [c.metric, c.status, c.details]),
        theme: 'striped',
        headStyles: { fillColor: COLORS.primary, textColor: COLORS.white },
        columnStyles: {
            1: { cellWidth: 30, fontStyle: 'bold', halign: 'center' }
        },
        didParseCell: (data) => {
             if (data.section === 'body' && data.column.index === 1) {
                const status = data.cell.raw;
                if (status === 'Pass') data.cell.styles.textColor = COLORS.success;
                if (status === 'Fail') data.cell.styles.textColor = COLORS.danger;
                if (status === 'Warning') data.cell.styles.textColor = COLORS.warning;
            }
        }
    });
};

const generateCategoryAnalysis = (doc: jsPDF, data: DetailedReportContent['categoryAnalysis'], chartImg: string) => {
    doc.addPage();
    addHeader(doc, "Category Performance");
    
    let y = 60;
    
    // Table
    autoTable(doc, {
        startY: y,
        head: [['Category', 'Item Count', 'Revenue', 'Profit', 'Margin %']],
        body: data.map(c => [
            c.category,
            c.itemCount,
            `$${c.revenue.toLocaleString()}`,
            `$${c.profit.toLocaleString()}`,
            `${c.margin.toFixed(1)}%`
        ]),
        theme: 'striped',
        headStyles: { fillColor: COLORS.secondary },
        columnStyles: {
            2: { halign: 'right' },
            3: { halign: 'right', fontStyle: 'bold' },
            4: { halign: 'right' }
        }
    });

    // Chart
    const finalY = (doc as any).lastAutoTable.finalY + 15;
    if (finalY + 90 < doc.internal.pageSize.getHeight()) {
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(COLORS.primary);
        doc.text("Revenue Distribution by Category", PAGE_MARGIN, finalY);
        
        // Centered Chart
        doc.addImage(chartImg, 'PNG', PAGE_MARGIN + 25, finalY + 5, 120, 80);
    }
};

const generateMarketAnalysis = (doc: jsPDF, data: DetailedReportContent['marketAnalysis'], priceChartImg: string) => {
    doc.addPage();
    addHeader(doc, "Market Analysis");
    
    let y = 60;
    
    // Top Performers
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text("Top Performing Products", PAGE_MARGIN, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    data.topPerformers.forEach(item => {
        doc.text(`• ${item}`, PAGE_MARGIN + 5, y);
        y += 5;
    });
    y += 5;

    // Opportunities
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text("Opportunity Gaps", PAGE_MARGIN, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    data.opportunityGaps.forEach(item => {
        doc.text(`• ${item}`, PAGE_MARGIN + 5, y);
        y += 5;
    });
    y += 10;

    // Price Chart
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(COLORS.primary);
    doc.text("Product Price Range Distribution", PAGE_MARGIN, y);
    doc.addImage(priceChartImg, 'PNG', PAGE_MARGIN, y + 5, 170, 80);
}

const generateStrategicRecommendations = (doc: jsPDF, recommendations: DetailedReportContent['strategicRecommendations']) => {
    doc.addPage();
    addHeader(doc, "Strategic Recommendations");
    
    let y = 60;

    recommendations.forEach(rec => {
        // Priority Badge
        let badgeColor = COLORS.success;
        if (rec.priority === 'High') badgeColor = COLORS.danger;
        if (rec.priority === 'Medium') badgeColor = COLORS.warning;
        
        doc.setFillColor(badgeColor);
        doc.roundedRect(PAGE_MARGIN, y, 20, 6, 1, 1, 'F');
        doc.setTextColor(COLORS.white);
        doc.setFontSize(7);
        doc.setFont('helvetica', 'bold');
        doc.text(rec.priority.toUpperCase(), PAGE_MARGIN + 2, y + 4.5);

        // Title
        doc.setTextColor(COLORS.textDark);
        doc.setFontSize(12);
        doc.text(rec.title, PAGE_MARGIN + 25, y + 5);
        y += 10;

        // Description
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(COLORS.textLight);
        const descLines = doc.splitTextToSize(rec.description, 170);
        doc.text(descLines, PAGE_MARGIN, y);
        y += descLines.length * 5 + 3;

        // Impact
        doc.setFontSize(9);
        doc.setTextColor(COLORS.primary);
        doc.setFont('helvetica', 'italic');
        doc.text(`Projected Impact: ${rec.impact}`, PAGE_MARGIN, y);
        
        // Divider
        y += 8;
        doc.setDrawColor(220);
        doc.setLineWidth(0.2);
        doc.line(PAGE_MARGIN, y, 190, y);
        y += 10;

        // Page break check
        if (y > 250) {
            doc.addPage();
            addHeader(doc, "Strategic Recommendations (Cont.)");
            y = 60;
        }
    });
};

const generateProductTable = (doc: jsPDF, products: any[]) => {
    doc.addPage();
    addHeader(doc, "Detailed Product Inventory");

    autoTable(doc, {
        startY: 60,
        head: [['Product Name', 'Category', 'Price', 'Sold/Wk', 'Margin', 'Profit/Wk']],
        body: products.map(p => [
            p.name,
            p.category || '-',
            `$${p.sellingPrice.toFixed(2)}`,
            p.unitsSoldWeek,
            `${p.margin.toFixed(1)}%`,
            `$${p.weeklyProfit.toFixed(2)}`
        ]),
        theme: 'plain',
        headStyles: { fillColor: COLORS.primary, textColor: COLORS.white },
        styles: { fontSize: 8, cellPadding: 2 },
        alternateRowStyles: { fillColor: COLORS.bgLight }
    });
};

// --- Main Generator Function ---

export const generatePdfReport = async ({ reportContent, metrics, products, aiInsights }: ReportData) => {
    
    // --- Data Preparation for Charts ---
    
    // 1. Profit Trend Chart Data (Using 7 simulated points from dashboardMetrics)
    // The metrics.profitTrend comes as an array of 7 numbers.
    const trendLabels = ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5', 'Day 6', 'Current'];
    const trendChartData = {
        labels: trendLabels,
        datasets: [{
            label: 'Weekly Profit ($)',
            data: metrics.profitTrend || [0,0,0,0,0,0,0],
            borderColor: COLORS.secondary,
            backgroundColor: 'rgba(59, 130, 246, 0.2)',
            fill: true,
            tension: 0.4,
            pointRadius: 3
        }]
    };
    
    // 2. Category Revenue Chart Data
    const categoryData = reportContent.categoryAnalysis;
    const categoryChartData = {
        labels: categoryData.map(c => c.category),
        datasets: [{
            data: categoryData.map(c => c.revenue),
            backgroundColor: [
                '#3b82f6', '#10b981', '#f59e0b', '#6366f1', '#ec4899', '#8b5cf6'
            ]
        }]
    };

    // 3. Price Range Distribution Chart Data
    // We need to bucket the products
    const ranges = {
        'Under $10': 0,
        '$10 - $25': 0,
        '$25 - $50': 0,
        '$50+': 0
    };
    products.forEach(p => {
        if (p.sellingPrice < 10) ranges['Under $10']++;
        else if (p.sellingPrice < 25) ranges['$10 - $25']++;
        else if (p.sellingPrice < 50) ranges['$25 - $50']++;
        else ranges['$50+']++;
    });
    
    const priceChartData = {
        labels: Object.keys(ranges),
        datasets: [{
            label: 'Number of Products',
            data: Object.values(ranges),
            backgroundColor: COLORS.primary,
            barThickness: 40
        }]
    };

    // --- Generate Images ---
    
    const trendChartImg = await generateChartImage('line', trendChartData, {
        plugins: { legend: { display: false } },
        scales: { y: { beginAtZero: true } }
    });

    const categoryChartImg = await generateChartImage('doughnut', categoryChartData, {
        cutout: '50%',
        plugins: { legend: { position: 'right' } }
    });

    const priceChartImg = await generateChartImage('bar', priceChartData, {
        plugins: { legend: { display: false } },
        scales: { y: { beginAtZero: true, title: { display: true, text: 'Count' } } }
    });


    // --- PDF Construction ---
    
    const doc = new jsPDF();
    
    // 1. Cover Page
    generateCoverPage(doc, reportContent);

    // 2. Table of Contents
    generateTOC(doc);

    // 3. Executive Summary (with Trend Chart)
    generateExecutiveSummary(doc, reportContent.executiveSummary, trendChartImg);

    // 4. Data Quality
    generateDataQuality(doc, reportContent.dataQuality);

    // 5. Category Analysis (with Pie Chart)
    generateCategoryAnalysis(doc, reportContent.categoryAnalysis, categoryChartImg);

    // 6. Market Analysis (with Price Bar Chart)
    generateMarketAnalysis(doc, reportContent.marketAnalysis, priceChartImg);

    // 7. Strategic Recommendations
    generateStrategicRecommendations(doc, reportContent.strategicRecommendations);

    // 8. Product Data
    generateProductTable(doc, products);

    // Footer on all pages
    addFooter(doc);

    doc.save(`MSPCC_Audit_Report_${new Date().toISOString().substring(0, 10)}.pdf`);
};